# This project is developed and tested with Flutter 3.29.2
# You do NOT need FVM to run it. Please use Flutter 3.29.2 for best compatibility.

name: products
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.29.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  get_it: ^8.0.3
  injectable: ^2.1.0
  bloc: ^9.0.0
  meta: ^1.16.0
  mocktail: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  injectable_generator: ^2.1.0
  build_runner: ^2.4.0
  auto_route: ^10.1.0+1
  auto_route_generator: ^10.1.0
  bloc_test: ^10.0.0

flutter:
  uses-material-design: true

